/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
static yyconst short int yy_accept[155] =
    {   0,
        0,    0,   72,   71,   70,   28,   69,   24,   68,   64,
       66,   17,    6,   65,   51,   52,   15,   13,   31,   14,
       62,   16,    1,    1,   21,   53,    9,   32,   10,   48,
       23,    1,    1,   49,   67,   50,    5,   60,   29,    4,
       30,   61,   71,   71,   71,    8,    0,   54,    0,   35,
        3,   44,    0,    0,   27,   33,   19,   55,   36,   20,
       37,   47,    0,    0,   26,   18,   34,   57,    1,    1,
        1,    1,    1,    1,   22,   41,   11,    7,   12,   42,
        0,    0,    1,   45,   46,    2,   58,    0,    0,   56,
        0,   55,   63,    0,    0,    0,   25,   57,   57,    0,

        0,    1,    0,    1,   38,   39,   43,    0,    1,    0,
       56,    0,    0,    0,    0,    0,   57,    0,    0,    1,
       40,    0,    1,    0,   57,    0,    0,    0,    0,    0,
        1,   57,   57,    0,   57,    0,   57,    0,    1,   57,
       57,    0,    1,    0,    1,    0,    1,   59,    1,    0,
        1,    1,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   30,   31,   30,
       32,   33,   32,   32,   32,   34,   32,   35,   32,   36,
       32,   32,   32,   32,   32,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   32,   42,   43,   44,   45,   30,

       46,   47,   32,   32,   48,   32,   32,   49,   50,   51,
       32,   36,   32,   52,   32,   53,   54,   55,   32,   56,
       32,   32,   57,   58,   59,   60,    1,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,    1,    1,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   64,
       64,   64,   64,   64,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    1,    1,    1,    1,    1,    3,    1,    6,    6,
        6,    1,    1,    1,    1,    7,    1,    1,    3,    1,
        1,    1,    5,    5,    6,    6,    5,    1,    1,    1,
        3,    3,    3,    3,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[161] =
    {   0,
        0,    0,  346,  347,  347,  347,  347,  320,   59,  347,
      347,  319,   56,  290,  347,  347,   48,   54,  347,   51,
       62,   70,   81,   41,  298,  347,   61,  292,   62,  347,
       90,  121,  269,  347,  347,  347,  289,  347,  347,   45,
      347,  347,  252,  251,  250,  347,   84,  347,    0,  347,
      347,  347,  298,    0,  347,  347,  347,   71,  347,  347,
      347,  347,  290,  126,  293,  347,  347,  129,   63,    0,
        0,  163,    0,  167,  347,  271,  347,  347,  347,   81,
       92,  244,  238,  347,  347,  347,  347,  214,  204,  347,
      250,  347,  347,  161,   88,  184,  347,  195,  347,  202,

      101,  124,    0,  223,  347,  347,  234,  202,  204,  173,
      217,  212,  143,  141,  173,  145,  210,  215,  188,    0,
      347,  175,  155,  217,  226,  243,  251,  170,  259,  150,
      145,  257,  228,  230,  263,  265,  269,  143,  140,  347,
      347,  136,  117,  108,  105,   97,   55,  347,  182,   57,
      285,  271,    0,  347,  318,  325,  330,  333,  334,  336
    } ;

static yyconst short int yy_def[161] =
    {   0,
      154,    1,  154,  154,  154,  154,  154,  154,  155,  154,
      154,  154,  154,  156,  154,  154,  154,  154,  154,  154,
      154,  154,  154,   23,  154,  154,  154,  154,  154,  154,
      154,   23,   32,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  155,  154,  157,  154,
      154,  154,  154,  158,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,   23,   32,
       32,   32,   32,   32,  154,  154,  154,  154,  154,  154,
      154,  154,   32,  154,  154,  154,  154,  154,  154,  154,
      158,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,   32,  159,   74,  154,  154,  154,  154,   32,  154,
      158,  154,  154,  154,  154,  154,  154,  154,  160,  104,
      154,  154,   32,  154,  154,  154,  154,  160,  154,  154,
       32,  154,  154,  154,  154,  154,  154,  154,   32,  154,
      154,  154,   32,  154,   32,  154,   32,  154,   32,  154,
       32,   32,   32,    0,  154,  154,  154,  154,  154,  154
    } ;

static yyconst short int yy_nxt[412] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   32,   33,   32,   32,   32,   32,   34,   35,   36,
       37,   38,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   39,   40,   41,   42,
        4,   43,   44,   45,   48,   51,   55,   60,   57,   85,
       58,   58,   56,   58,   58,   61,   62,   70,   59,   63,
       52,   64,   64,   65,   76,   77,   79,   80,   66,   48,
       58,   58,  129,   81,   67,   81,   70,   49,   68,   70,

       69,   69,   86,  149,   92,  106,  107,  113,  113,   70,
       71,   72,   70,   70,   73,   70,   70,   74,   70,   92,
      118,  118,   49,   70,   70,   70,   72,   71,   70,   73,
       70,   70,   70,   70,   70,   70,   74,   82,  154,   82,
       70,   70,  148,  102,  102,   94,   94,  147,   98,   98,
       70,   70,  146,   71,   70,   95,   96,   70,   99,  100,
      115,  115,  113,  113,  117,  117,   70,   70,  145,   70,
       71,   96,   95,  126,  100,   99,   70,  101,  144,  101,
       94,   94,  102,  102,  103,  143,  104,  104,  126,  142,
       95,  112,  127,  127,  139,  104,  104,  104,  114,  150,

      114,  138,   95,  115,  115,  129,  112,   95,  131,  104,
      104,  104,  104,  104,   98,   98,  116,  151,  116,   95,
      130,  117,  117,  129,   99,  100,  124,  111,  124,  117,
      117,  125,  125,   87,  118,  118,  125,  125,  123,   99,
      100,   99,  120,  120,   99,  132,  132,  113,  113,  135,
      135,  120,  120,  120,  122,  133,   99,  134,  121,  134,
      111,   99,  135,  135,  110,  120,  120,  120,  120,  120,
      127,  127,  133,  136,   87,  136,  132,  132,  137,  137,
       95,  126,  135,  135,  137,  137,  133,  126,  137,  137,
      152,  152,  140,  109,  108,  105,  126,   95,  141,  136,

      153,  136,  126,  133,  152,  152,   97,   93,   90,  140,
       89,   88,   87,   84,   83,  141,   78,  153,   47,   75,
       47,   47,   47,   47,   47,   53,   53,   53,   54,   53,
       53,   53,   47,   47,   47,   91,   91,   91,  119,  119,
      128,  128,  128,   50,   46,  154,    3,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154
    } ;

static yyconst short int yy_chk[412] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   13,   17,   20,   18,   40,
       20,   20,   17,   18,   18,   20,   20,   24,   18,   21,
       13,   21,   21,   22,   27,   27,   29,   29,   22,   47,
       58,   58,  150,   31,   22,   81,   24,    9,   23,   69,

       23,   23,   40,  147,   58,   80,   80,   95,   95,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   69,   58,
      101,  101,   47,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   31,   32,   81,
       32,   32,  146,  102,  102,   64,   64,  145,   68,   68,
       32,   32,  144,  102,   32,   64,   64,   32,   68,   68,
      114,  114,  113,  113,  116,  116,   32,   32,  143,   32,
      102,   64,   64,  113,   68,   68,   32,   72,  142,   72,
       94,   94,   72,   72,   74,  139,   74,   74,  113,  138,
       94,   94,  115,  115,  131,   74,   74,   74,   96,  149,

       96,  130,  115,   96,   96,  128,   94,   94,  123,   74,
       74,   74,   74,   74,   98,   98,  100,  149,  100,  115,
      122,  100,  100,  119,   98,   98,  112,  111,  112,  117,
      117,  112,  112,  110,  118,  118,  124,  124,  109,  117,
       98,   98,  104,  104,  118,  125,  125,  133,  133,  134,
      134,  104,  104,  104,  108,  125,  117,  126,  107,  126,
       91,  118,  126,  126,   89,  104,  104,  104,  104,  104,
      127,  127,  125,  129,   88,  129,  132,  132,  129,  129,
      127,  127,  135,  135,  136,  136,  132,  132,  137,  137,
      152,  152,  135,   83,   82,   76,  127,  127,  137,  151,

      152,  151,  132,  132,  151,  151,   65,   63,   53,  135,
       45,   44,   43,   37,   33,  137,   28,  152,  155,   25,
      155,  155,  155,  155,  155,  156,  156,  156,   14,  156,
      156,  156,  157,  157,  157,  158,  158,  158,  159,  159,
      160,  160,  160,   12,    8,    3,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "SLR\\wordParser.l"
#define INITIAL 0
#line 2 "SLR\\wordParser.l"
   #include "stdio.h"
   #include "stdlib.h"
   #include<string.h>
   #include "SLR\lex.yy.h"

    struct C_Lex_Word *lex_word=NULL;
    struct C_Lex_Word *p_lex_word=NULL;
    int buffer_size=0;
    int rest_size=0;

void write_word(char *yytext,char *symbol_name){

	int incremential = 32000;

	if(rest_size==0){
		struct C_Lex_Word * new_lex_word=(struct C_Lex_Word *)malloc(sizeof(struct C_Lex_Word)*(buffer_size+ incremential+1));
		int i1=0;
		for(i1=0;i1<(buffer_size+ incremential);i1++){
			if(i1<buffer_size){
				/*
				new_lex_word[i1].type=lex_word[i1].type;
				new_lex_word[i1].content=lex_word[i1].content;
				*/
				new_lex_word[i1].type = (char *)malloc(sizeof(char)*(strlen(lex_word[i1].type) + 1));
				strcpy(new_lex_word[i1].type, lex_word[i1].type);
				new_lex_word[i1].content = (char *)malloc(sizeof(char)*(strlen(lex_word[i1].content) + 1));
				strcpy(new_lex_word[i1].content, lex_word[i1].content);
				free(lex_word[i1].type);
				free(lex_word[i1].content);
				
			}else{
				new_lex_word[i1].type=NULL;
				new_lex_word[i1].content=NULL;			
			}
		}
		free(lex_word);
		lex_word=new_lex_word;
		p_lex_word=new_lex_word+buffer_size;
		buffer_size+= incremential;
		rest_size=buffer_size;
	}

  p_lex_word->content = (char *)malloc(sizeof(char)*(strlen(yytext)+1));
  strcpy(p_lex_word->content, yytext);
  p_lex_word->type = (char *)malloc(sizeof(char)*(strlen(symbol_name)+1));
  strcpy(p_lex_word->type, symbol_name);
  rest_size--;
  p_lex_word++;
}


#line 559 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 82 "SLR\\wordParser.l"





#line 716 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 155 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 347 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "SLR\\wordParser.l"
{
  write_word(yytext,"'IDENTIFIER'");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 94 "SLR\\wordParser.l"
{
  write_word(yytext,"'OR'");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "SLR\\wordParser.l"
{
  write_word(yytext,"'AND'");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 102 "SLR\\wordParser.l"
{
  write_word(yytext,"'BIT_OR'");
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 106 "SLR\\wordParser.l"
{
  write_word(yytext,"'CARET'");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 110 "SLR\\wordParser.l"
{
  write_word(yytext,"'BIT_AND'");
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 114 "SLR\\wordParser.l"
{
  write_word(yytext,"'DB_EQUAL'");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 118 "SLR\\wordParser.l"
{
  write_word(yytext,"'NOT_EQUAL'");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 122 "SLR\\wordParser.l"
{
  write_word(yytext,"'LEFT_ANGLE_BRACKET'");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_ANGLE_BRACKET'");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "SLR\\wordParser.l"
{
  write_word(yytext,"'LT_EQUAL'");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 138 "SLR\\wordParser.l"
{
  write_word(yytext,"'GT_EQUAL'");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 145 "SLR\\wordParser.l"
{
  write_word(yytext,"'PLUS'");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 149 "SLR\\wordParser.l"
{
  write_word(yytext,"'SUBTRACT'");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 153 "SLR\\wordParser.l"
{
  write_word(yytext,"'STAR'");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 157 "SLR\\wordParser.l"
{
  write_word(yytext,"'SLASH'");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 "SLR\\wordParser.l"
{
  write_word(yytext,"'PRECENTAGE'");
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 167 "SLR\\wordParser.l"
{
  write_word(yytext,"'COMMENT1'");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 171 "SLR\\wordParser.l"
{
  write_word(yytext,"'TWO_PLUS'");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 175 "SLR\\wordParser.l"
{
  write_word(yytext,"'TWO_SUBTRACT'");
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 179 "SLR\\wordParser.l"
{
  write_word(yytext,"'COLON'");
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 183 "SLR\\wordParser.l"
{
  write_word(yytext,"'TWO_COLON'");
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 187 "SLR\\wordParser.l"
{
  write_word(yytext,"'AT'");
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 191 "SLR\\wordParser.l"
{
  write_word(yytext,"'SURPRISE'");
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 197 "SLR\\wordParser.l"
{
  write_word(yytext,"'COMMENT2'");
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 201 "SLR\\wordParser.l"
{
  write_word(yytext,"'COMMENT3'");
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 205 "SLR\\wordParser.l"
{
  write_word(yytext,"'END_COMMENT'");
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 210 "SLR\\wordParser.l"
{
  write_word(yytext,"'NEXT_LINE'");
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 215 "SLR\\wordParser.l"
{
  write_word(yytext,"'LEFT_BRACE'");
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 219 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_BRACE'");
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 225 "SLR\\wordParser.l"
{
  write_word(yytext,"'COMMA'");
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 229 "SLR\\wordParser.l"
{
  write_word(yytext,"'EQUAL'");
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "SLR\\wordParser.l"
{
  write_word(yytext,"'MULTI_EQUAL'");
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 237 "SLR\\wordParser.l"
{
  write_word(yytext,"'DIVIDE_EQUAL'");
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 241 "SLR\\wordParser.l"
{
  write_word(yytext,"'PRECENTAGE_EQUAL'");
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "SLR\\wordParser.l"
{
  write_word(yytext,"'PLUS_EQUAL'");
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 251 "SLR\\wordParser.l"
{
  write_word(yytext,"'SUBTRACT_EQUAL'");
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 255 "SLR\\wordParser.l"
{
  write_word(yytext,"'LEFT_SHIFT_EQUAL'");
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 259 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_SHIFT_EQUAL'");
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 263 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_SHIFT2_EQUAL'");
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 267 "SLR\\wordParser.l"
{
  write_word(yytext,"'LEFT_SHIFT'");
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 271 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_SHIFT'");
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 275 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_SHIFT2'");
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 279 "SLR\\wordParser.l"
{
  write_word(yytext,"'AND_EQUAL'");
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 283 "SLR\\wordParser.l"
{
  write_word(yytext,"'XOR_EQUAL'");
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 287 "SLR\\wordParser.l"
{
  write_word(yytext,"'OR_EQUAL'");
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 291 "SLR\\wordParser.l"
{
  write_word(yytext,"'LAMBDA_TO'");
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 296 "SLR\\wordParser.l"
{
  write_word(yytext,"'QUESTION'");
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 300 "SLR\\wordParser.l"
{
  write_word(yytext,"'LEFT_BRACKET'");
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 304 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_BRACKET'");
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 308 "SLR\\wordParser.l"
{
  write_word(yytext,"'LEFT_PARENTHESES'");
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 312 "SLR\\wordParser.l"
{
  write_word(yytext,"'RIGHT_PARENTHESES'");
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 316 "SLR\\wordParser.l"
{
  write_word(yytext,"'semicolon'");
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 320 "SLR\\wordParser.l"
{
  write_word(yytext,"'StringLiteral'");
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 324 "SLR\\wordParser.l"
{
  write_word(yytext,"'IntegerLiteral'");
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 328 "SLR\\wordParser.l"
{
  write_word(yytext,"'CharacterLiteral'");
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 332 "SLR\\wordParser.l"
{
  write_word(yytext,"'FloatingPointLiteral'");
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 336 "SLR\\wordParser.l"
{
  write_word(yytext,"'NO_ENGLISH_CH'");
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 340 "SLR\\wordParser.l"
{
  write_word(yytext,"'AT_INTERFACE'");
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 345 "SLR\\wordParser.l"
{
  write_word(yytext,"'EXE_QUOTES'");
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 349 "SLR\\wordParser.l"
{
  write_word(yytext,"'TILDE'");
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 355 "SLR\\wordParser.l"
{
  write_word(yytext,"'SPOT'");
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 359 "SLR\\wordParser.l"
{
  write_word(yytext,"'THREE_SPOT'");
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 369 "SLR\\wordParser.l"
{
  write_word(yytext,"'POUND'");
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 373 "SLR\\wordParser.l"
{
  write_word(yytext,"'SINGLE_QUOTES'");
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 377 "SLR\\wordParser.l"
{
  write_word(yytext,"'DOLLAR'");
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 383 "SLR\\wordParser.l"
{
  write_word(yytext,"'BACK_SLASH'");
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 387 "SLR\\wordParser.l"
{
  write_word(yytext,"'DOUBLE_QUOTES'");
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 394 "SLR\\wordParser.l"
{}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 396 "SLR\\wordParser.l"
{

}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 400 "SLR\\wordParser.l"
ECHO;
	YY_BREAK
#line 1292 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 155 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 155 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 154);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( _fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 400 "SLR\\wordParser.l"


void c_word_parser(char* file_path,struct C_Lex_Word **beg,struct C_Lex_Word **end){

   fopen_s(&yyin, file_path, "r");
   yylex();
   fclose(yyin);
   *beg=lex_word;
   *end=p_lex_word;
}

void c_free(){
	int i1;
   for(i1=0;i1<buffer_size;i1++){
	if(lex_word[i1].type!=NULL){
	   free(lex_word[i1].type);
	   lex_word[i1].type=NULL;
	}

    if(lex_word[i1].content!=NULL){
	   free(lex_word[i1].content);
	   lex_word[i1].content=NULL;
	}
   }

    free(lex_word);
    lex_word=NULL;

    p_lex_word=NULL;
	buffer_size=0;
	rest_size=0;
}


int yywrap()

{
    return 1;
}
